### ISSUE TITLE
The Ghostfence is broken

### ISSUE THREAD

**Issue by zaphida** [zesterer/openmw-volumetric-clouds#10]
With replace skybox and clouds enabled, gaps appear in the Ghostfence.
[broken ghostfence.webm](https://user-images.githubusercontent.com/12946330/186872719-46fccc5c-695d-4fbd-b798-5306c93d85b9.webm)
The sections of ghost fence where there is terrain behind it appear normal, but any section through which you can see only sky becomes 100% transparent.
The issue is not unique to the Ghostfence. Look straight up at the sky and cast a spell, and the spell's visual effects are not visible.

**Comment by zesterer** [comment]
This is another case of #7. Unfortunately, OpenMW just doesn't expose enough information about translucent surfaces for the mod to be able to produce correct behaviour in these cases. It's unlikely that this will ever be *completely* fixed because [transparency is hard](https://shaderfun.com/2020/09/20/why-transparency-is-hard/) for all but the most trivial shader effects (volumetric fog is not a trivial shader effect). Partially fixing it would require pretty substantial changes to OpenMW as mentioned in #7.
